/// Model for a single Android settings intent entry.
class SettingIntent {
  final String id;
  final String text;
  final String intent;

  const SettingIntent({
    required this.id,
    required this.text,
    required this.intent,
  });
}

/// Full list of Android settings intents, mirrored from the reference project.
const List<SettingIntent> kSettingsIntents = [
  SettingIntent(id: 'settings', text: 'Settings', intent: 'android.settings.SETTINGS'),
  SettingIntent(id: 'apn_settings', text: 'APN Settings', intent: 'android.settings.APN_SETTINGS'),
  SettingIntent(id: 'location_source_settings', text: 'Location Source Settings', intent: 'android.settings.LOCATION_SOURCE_SETTINGS'),
  SettingIntent(id: 'location_controller_extra_package_settings', text: 'Location Controller Extra Package Settings', intent: 'android.settings.LOCATION_CONTROLLER_EXTRA_PACKAGE_SETTINGS'),
  SettingIntent(id: 'location_scanning_settings', text: 'Location Scanning Settings', intent: 'android.settings.LOCATION_SCANNING_SETTINGS'),
  SettingIntent(id: 'manage_cloned_apps_settings', text: 'Manage Cloned Apps Settings', intent: 'android.settings.MANAGE_CLONED_APPS_SETTINGS'),
  SettingIntent(id: 'user_settings', text: 'User Settings', intent: 'android.settings.USER_SETTINGS'),
  SettingIntent(id: 'wireless_settings', text: 'Wireless Settings', intent: 'android.settings.WIRELESS_SETTINGS'),
  SettingIntent(id: 'tether_provisioning_ui', text: 'Tether Provisioning UI', intent: 'android.settings.TETHER_PROVISIONING_UI'),
  SettingIntent(id: 'tether_unsupported_carrier_ui', text: 'Tether Unsupported Carrier UI', intent: 'android.settings.TETHER_UNSUPPORTED_CARRIER_UI'),
  SettingIntent(id: 'airplane_mode_settings', text: 'Airplane Mode Settings', intent: 'android.settings.AIRPLANE_MODE_SETTINGS'),
  SettingIntent(id: 'mobile_data_usage', text: 'Mobile Data Usage', intent: 'android.settings.MOBILE_DATA_USAGE'),
  SettingIntent(id: 'one_handed_settings', text: 'One-Handed Settings', intent: 'android.settings.action.ONE_HANDED_SETTINGS'),
  SettingIntent(id: 'voice_control_airplane_mode', text: 'Voice Control Airplane Mode', intent: 'android.settings.VOICE_CONTROL_AIRPLANE_MODE'),
  SettingIntent(id: 'accessibility_settings', text: 'Accessibility Settings', intent: 'android.settings.ACCESSIBILITY_SETTINGS'),
  SettingIntent(id: 'accessibility_details_settings', text: 'Accessibility Details Settings', intent: 'android.settings.ACCESSIBILITY_DETAILS_SETTINGS'),
  SettingIntent(id: 'accessibility_color_motion_settings', text: 'Accessibility Color Motion Settings', intent: 'android.settings.ACCESSIBILITY_COLOR_MOTION_SETTINGS'),
  SettingIntent(id: 'reduce_bright_colors_settings', text: 'Reduce Bright Colors Settings', intent: 'android.settings.REDUCE_BRIGHT_COLORS_SETTINGS'),
  SettingIntent(id: 'accessibility_color_space_settings', text: 'Accessibility Color Space Settings', intent: 'com.android.settings.ACCESSIBILITY_COLOR_SPACE_SETTINGS'),
  SettingIntent(id: 'color_inversion_settings', text: 'Color Inversion Settings', intent: 'android.settings.COLOR_INVERSION_SETTINGS'),
  SettingIntent(id: 'text_reading_settings', text: 'Text Reading Settings', intent: 'android.settings.TEXT_READING_SETTINGS'),
  SettingIntent(id: 'usage_access_settings', text: 'Usage Access Settings', intent: 'android.settings.USAGE_ACCESS_SETTINGS'),
  SettingIntent(id: 'usage_access_config', text: 'Usage Access Config', intent: 'android.intent.category.USAGE_ACCESS_CONFIG'),
  SettingIntent(id: 'usage_access_reason', text: 'Usage Access Reason', intent: 'android.settings.metadata.USAGE_ACCESS_REASON'),
  SettingIntent(id: 'security_settings', text: 'Security Settings', intent: 'android.settings.SECURITY_SETTINGS'),
  SettingIntent(id: 'manage_unknown_app_sources', text: 'Manage Unknown App Sources', intent: 'android.settings.MANAGE_UNKNOWN_APP_SOURCES'),
  SettingIntent(id: 'request_schedule_exact_alarm', text: 'Request Schedule Exact Alarm', intent: 'android.settings.REQUEST_SCHEDULE_EXACT_ALARM'),
  SettingIntent(id: 'request_manage_media', text: 'Request Manage Media', intent: 'android.settings.REQUEST_MANAGE_MEDIA'),
  SettingIntent(id: 'manage_app_long_running_jobs', text: 'Manage App Long Running Jobs', intent: 'android.settings.MANAGE_APP_LONG_RUNNING_JOBS'),
  SettingIntent(id: 'manage_cross_profile_access', text: 'Manage Cross Profile Access', intent: 'android.settings.MANAGE_CROSS_PROFILE_ACCESS'),
  SettingIntent(id: 'app_open_by_default_settings', text: 'App Open By Default Settings', intent: 'android.settings.APP_OPEN_BY_DEFAULT_SETTINGS'),
  SettingIntent(id: 'trusted_credentials_user', text: 'Trusted Credentials User', intent: 'com.android.settings.TRUSTED_CREDENTIALS_USER'),
  SettingIntent(id: 'monitoring_cert_info', text: 'Monitoring Cert Info', intent: 'com.android.settings.MONITORING_CERT_INFO'),
  SettingIntent(id: 'privacy_settings', text: 'Privacy Settings', intent: 'android.settings.PRIVACY_SETTINGS'),
  SettingIntent(id: 'vpn_settings', text: 'VPN Settings', intent: 'android.settings.VPN_SETTINGS'),
  SettingIntent(id: 'wifi_settings', text: 'WiFi Settings', intent: 'android.settings.WIFI_SETTINGS'),
  SettingIntent(id: 'advanced_memory_protection_settings', text: 'Advanced Memory Protection Settings', intent: 'android.settings.ADVANCED_MEMORY_PROTECTION_SETTINGS'),
  SettingIntent(id: 'wifi_ip_settings', text: 'WiFi IP Settings', intent: 'android.settings.WIFI_IP_SETTINGS'),
  SettingIntent(id: 'process_wifi_easy_connect_uri', text: 'Process WiFi Easy Connect URI', intent: 'android.settings.PROCESS_WIFI_EASY_CONNECT_URI'),
  SettingIntent(id: 'data_usage_settings', text: 'Data Usage Settings', intent: 'android.settings.DATA_USAGE_SETTINGS'),
  SettingIntent(id: 'bluetooth_settings', text: 'Bluetooth Settings', intent: 'android.settings.BLUETOOTH_SETTINGS'),
  SettingIntent(id: 'app_search_settings', text: 'App Search Settings', intent: 'android.settings.APP_SEARCH_SETTINGS'),
  SettingIntent(id: 'assist_gesture_settings', text: 'Assist Gesture Settings', intent: 'android.settings.ASSIST_GESTURE_SETTINGS'),
  SettingIntent(id: 'fingerprint_enroll', text: 'Fingerprint Enroll', intent: 'android.settings.FINGERPRINT_ENROLL'),
  SettingIntent(id: 'biometric_enroll', text: 'Biometric Enroll', intent: 'android.settings.BIOMETRIC_ENROLL'),
  SettingIntent(id: 'cast_settings', text: 'Cast Settings', intent: 'android.settings.CAST_SETTINGS'),
  SettingIntent(id: 'date_settings', text: 'Date Settings', intent: 'android.settings.DATE_SETTINGS'),
  SettingIntent(id: 'sound_settings', text: 'Sound Settings', intent: 'android.settings.SOUND_SETTINGS'),
  SettingIntent(id: 'display_settings', text: 'Display Settings', intent: 'android.settings.DISPLAY_SETTINGS'),
  SettingIntent(id: 'auto_rotate_settings', text: 'Auto Rotate Settings', intent: 'android.settings.AUTO_ROTATE_SETTINGS'),
  SettingIntent(id: 'night_display_settings', text: 'Night Display Settings', intent: 'android.settings.NIGHT_DISPLAY_SETTINGS'),
  SettingIntent(id: 'dark_theme_settings', text: 'Dark Theme Settings', intent: 'android.settings.DARK_THEME_SETTINGS'),
  SettingIntent(id: 'locale_settings', text: 'Locale Settings', intent: 'android.settings.LOCALE_SETTINGS'),
  SettingIntent(id: 'app_locale_settings', text: 'App Locale Settings', intent: 'android.settings.APP_LOCALE_SETTINGS'),
  SettingIntent(id: 'regional_preferences_settings', text: 'Regional Preferences Settings', intent: 'android.settings.REGIONAL_PREFERENCES_SETTINGS'),
  SettingIntent(id: 'lock_screen_settings', text: 'Lock Screen Settings', intent: 'android.settings.LOCK_SCREEN_SETTINGS'),
  SettingIntent(id: 'bluetooth_pairing_settings', text: 'Bluetooth Pairing Settings', intent: 'android.settings.BLUETOOTH_PAIRING_SETTINGS'),
  SettingIntent(id: 'voice_input_settings', text: 'Voice Input Settings', intent: 'android.settings.VOICE_INPUT_SETTINGS'),
  SettingIntent(id: 'input_method_settings', text: 'Input Method Settings', intent: 'android.settings.INPUT_METHOD_SETTINGS'),
  SettingIntent(id: 'input_method_subtype_settings', text: 'Input Method Subtype Settings', intent: 'android.settings.INPUT_METHOD_SUBTYPE_SETTINGS'),
  SettingIntent(id: 'user_dictionary_settings', text: 'User Dictionary Settings', intent: 'android.settings.USER_DICTIONARY_SETTINGS'),
  SettingIntent(id: 'hard_keyboard_settings', text: 'Hard Keyboard Settings', intent: 'android.settings.HARD_KEYBOARD_SETTINGS'),
  SettingIntent(id: 'user_dictionary_insert', text: 'User Dictionary Insert', intent: 'com.android.settings.USER_DICTIONARY_INSERT'),
  SettingIntent(id: 'application_settings', text: 'Application Settings', intent: 'android.settings.APPLICATION_SETTINGS'),
  SettingIntent(id: 'application_development_settings', text: 'Application Development Settings', intent: 'android.settings.APPLICATION_DEVELOPMENT_SETTINGS'),
  SettingIntent(id: 'quick_launch_settings', text: 'Quick Launch Settings', intent: 'android.settings.QUICK_LAUNCH_SETTINGS'),
  SettingIntent(id: 'manage_applications_settings', text: 'Manage Applications Settings', intent: 'android.settings.MANAGE_APPLICATIONS_SETTINGS'),
  SettingIntent(id: 'manage_all_applications_settings', text: 'Manage All Applications Settings', intent: 'android.settings.MANAGE_ALL_APPLICATIONS_SETTINGS'),
  SettingIntent(id: 'manage_all_sim_profiles_settings', text: 'Manage All SIM Profiles Settings', intent: 'android.settings.MANAGE_ALL_SIM_PROFILES_SETTINGS'),
  SettingIntent(id: 'manage_overlay_permission', text: 'Manage Overlay Permission', intent: 'android.settings.action.MANAGE_OVERLAY_PERMISSION'),
  SettingIntent(id: 'manage_app_overlay_permission', text: 'Manage App Overlay Permission', intent: 'android.settings.MANAGE_APP_OVERLAY_PERMISSION'),
  SettingIntent(id: 'manage_write_settings', text: 'Manage Write Settings', intent: 'android.settings.action.MANAGE_WRITE_SETTINGS'),
  SettingIntent(id: 'app_usage_settings', text: 'App Usage Settings', intent: 'android.settings.action.APP_USAGE_SETTINGS'),
  SettingIntent(id: 'application_details_settings', text: 'Application Details Settings', intent: 'android.settings.APPLICATION_DETAILS_SETTINGS'),
  SettingIntent(id: 'foreground_services_settings', text: 'Foreground Services Settings', intent: 'android.settings.FOREGROUND_SERVICES_SETTINGS'),
  SettingIntent(id: 'ignore_battery_optimization_settings', text: 'Ignore Battery Optimization Settings', intent: 'android.settings.IGNORE_BATTERY_OPTIMIZATION_SETTINGS'),
  SettingIntent(id: 'request_ignore_battery_optimizations', text: 'Request Ignore Battery Optimizations', intent: 'android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS'),
  SettingIntent(id: 'view_advanced_power_usage_detail', text: 'View Advanced Power Usage Detail', intent: 'android.settings.VIEW_ADVANCED_POWER_USAGE_DETAIL'),
  SettingIntent(id: 'ignore_background_data_restrictions_settings', text: 'Ignore Background Data Restrictions Settings', intent: 'android.settings.IGNORE_BACKGROUND_DATA_RESTRICTIONS_SETTINGS'),
  SettingIntent(id: 'app_ops_settings', text: 'App Ops Settings', intent: 'android.settings.APP_OPS_SETTINGS'),
  SettingIntent(id: 'system_update_settings', text: 'System Update Settings', intent: 'android.settings.SYSTEM_UPDATE_SETTINGS'),
  SettingIntent(id: 'managed_profile_settings', text: 'Managed Profile Settings', intent: 'android.settings.MANAGED_PROFILE_SETTINGS'),
  SettingIntent(id: 'sync_settings', text: 'Sync Settings', intent: 'android.settings.SYNC_SETTINGS'),
  SettingIntent(id: 'add_account_settings', text: 'Add Account Settings', intent: 'android.settings.ADD_ACCOUNT_SETTINGS'),
  SettingIntent(id: 'data_saver_settings', text: 'Data Saver Settings', intent: 'android.settings.DATA_SAVER_SETTINGS'),
  SettingIntent(id: 'network_operator_settings', text: 'Network Operator Settings', intent: 'android.settings.NETWORK_OPERATOR_SETTINGS'),
  SettingIntent(id: 'data_roaming_settings', text: 'Data Roaming Settings', intent: 'android.settings.DATA_ROAMING_SETTINGS'),
  SettingIntent(id: 'internal_storage_settings', text: 'Internal Storage Settings', intent: 'android.settings.INTERNAL_STORAGE_SETTINGS'),
  SettingIntent(id: 'memory_card_settings', text: 'Memory Card Settings', intent: 'android.settings.MEMORY_CARD_SETTINGS'),
  SettingIntent(id: 'search_settings', text: 'Search Settings', intent: 'android.search.action.SEARCH_SETTINGS'),
  SettingIntent(id: 'device_info_settings', text: 'Device Info Settings', intent: 'android.settings.DEVICE_INFO_SETTINGS'),
  SettingIntent(id: 'nfc_settings', text: 'NFC Settings', intent: 'android.settings.NFC_SETTINGS'),
  SettingIntent(id: 'nfc_sharing_settings', text: 'NFC Sharing Settings', intent: 'android.settings.NFCSHARING_SETTINGS'),
  SettingIntent(id: 'nfc_payment_settings', text: 'NFC Payment Settings', intent: 'android.settings.NFC_PAYMENT_SETTINGS'),
  SettingIntent(id: 'dream_settings', text: 'Dream Settings', intent: 'android.settings.DREAM_SETTINGS'),
  SettingIntent(id: 'communal_settings', text: 'Communal Settings', intent: 'android.settings.COMMUNAL_SETTINGS'),
  SettingIntent(id: 'notification_assistant_settings', text: 'Notification Assistant Settings', intent: 'android.settings.NOTIFICATION_ASSISTANT_SETTINGS'),
  SettingIntent(id: 'notification_listener_settings', text: 'Notification Listener Settings', intent: 'android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS'),
  SettingIntent(id: 'notification_listener_detail_settings', text: 'Notification Listener Detail Settings', intent: 'android.settings.NOTIFICATION_LISTENER_DETAIL_SETTINGS'),
  SettingIntent(id: 'notification_policy_access_settings', text: 'Notification Policy Access Settings', intent: 'android.settings.NOTIFICATION_POLICY_ACCESS_SETTINGS'),
  SettingIntent(id: 'notification_policy_access_detail_settings', text: 'Notification Policy Access Detail Settings', intent: 'android.settings.NOTIFICATION_POLICY_ACCESS_DETAIL_SETTINGS'),
  SettingIntent(id: 'condition_provider_settings', text: 'Condition Provider Settings', intent: 'android.settings.ACTION_CONDITION_PROVIDER_SETTINGS'),
  SettingIntent(id: 'captioning_settings', text: 'Captioning Settings', intent: 'android.settings.CAPTIONING_SETTINGS'),
  SettingIntent(id: 'print_settings', text: 'Print Settings', intent: 'android.settings.ACTION_PRINT_SETTINGS'),
  SettingIntent(id: 'zen_mode_settings', text: 'Zen Mode Settings', intent: 'android.settings.ZEN_MODE_SETTINGS'),
  SettingIntent(id: 'zen_mode_blocked_effects_settings', text: 'Zen Mode Blocked Effects Settings', intent: 'android.settings.ZEN_MODE_BLOCKED_EFFECTS_SETTINGS'),
  SettingIntent(id: 'zen_mode_onboarding', text: 'Zen Mode Onboarding', intent: 'android.settings.ZEN_MODE_ONBOARDING'),
  SettingIntent(id: 'zen_mode_priority_settings', text: 'Zen Mode Priority Settings', intent: 'android.settings.ZEN_MODE_PRIORITY_SETTINGS'),
  SettingIntent(id: 'zen_mode_automation_settings', text: 'Zen Mode Automation Settings', intent: 'android.settings.ZEN_MODE_AUTOMATION_SETTINGS'),
  SettingIntent(id: 'voice_control_do_not_disturb_mode', text: 'Voice Control Do Not Disturb Mode', intent: 'android.settings.VOICE_CONTROL_DO_NOT_DISTURB_MODE'),
  SettingIntent(id: 'zen_mode_schedule_rule_settings', text: 'Zen Mode Schedule Rule Settings', intent: 'android.settings.ZEN_MODE_SCHEDULE_RULE_SETTINGS'),
  SettingIntent(id: 'zen_mode_event_rule_settings', text: 'Zen Mode Event Rule Settings', intent: 'android.settings.ZEN_MODE_EVENT_RULE_SETTINGS'),
  SettingIntent(id: 'zen_mode_external_rule_settings', text: 'Zen Mode External Rule Settings', intent: 'android.settings.ZEN_MODE_EXTERNAL_RULE_SETTINGS'),
  SettingIntent(id: 'show_regulatory_info', text: 'Show Regulatory Info', intent: 'android.settings.SHOW_REGULATORY_INFO'),
  SettingIntent(id: 'device_name', text: 'Device Name', intent: 'android.settings.DEVICE_NAME'),
  SettingIntent(id: 'pairing_settings', text: 'Pairing Settings', intent: 'android.settings.PAIRING_SETTINGS'),
  SettingIntent(id: 'battery_saver_settings', text: 'Battery Saver Settings', intent: 'android.settings.BATTERY_SAVER_SETTINGS'),
  SettingIntent(id: 'voice_control_battery_saver_mode', text: 'Voice Control Battery Saver Mode', intent: 'android.settings.VOICE_CONTROL_BATTERY_SAVER_MODE'),
  SettingIntent(id: 'home_settings', text: 'Home Settings', intent: 'android.settings.HOME_SETTINGS'),
  SettingIntent(id: 'manage_default_apps_settings', text: 'Manage Default Apps Settings', intent: 'android.settings.MANAGE_DEFAULT_APPS_SETTINGS'),
  SettingIntent(id: 'manage_more_default_apps_settings', text: 'Manage More Default Apps Settings', intent: 'android.settings.MANAGE_MORE_DEFAULT_APPS_SETTINGS'),
  SettingIntent(id: 'notification_settings', text: 'Notification Settings', intent: 'android.settings.NOTIFICATION_SETTINGS'),
  SettingIntent(id: 'conversation_settings', text: 'Conversation Settings', intent: 'android.settings.CONVERSATION_SETTINGS'),
  SettingIntent(id: 'notification_history', text: 'Notification History', intent: 'android.settings.NOTIFICATION_HISTORY'),
  SettingIntent(id: 'all_apps_notification_settings', text: 'All Apps Notification Settings', intent: 'android.settings.ALL_APPS_NOTIFICATION_SETTINGS'),
  SettingIntent(id: 'all_apps_notification_settings_for_review', text: 'All Apps Notification Settings For Review', intent: 'android.settings.ALL_APPS_NOTIFICATION_SETTINGS_FOR_REVIEW'),
  SettingIntent(id: 'app_notification_settings', text: 'App Notification Settings', intent: 'android.settings.APP_NOTIFICATION_SETTINGS'),
  SettingIntent(id: 'channel_notification_settings', text: 'Channel Notification Settings', intent: 'android.settings.CHANNEL_NOTIFICATION_SETTINGS'),
  SettingIntent(id: 'app_notification_bubble_settings', text: 'App Notification Bubble Settings', intent: 'android.settings.APP_NOTIFICATION_BUBBLE_SETTINGS'),
  SettingIntent(id: 'action_app_notification_redaction', text: 'Action App Notification Redaction', intent: 'android.settings.ACTION_APP_NOTIFICATION_REDACTION'),
  SettingIntent(id: 'action_power_menu_settings', text: 'Action Power Menu Settings', intent: 'android.settings.ACTION_POWER_MENU_SETTINGS'),
  SettingIntent(id: 'action_device_controls_settings', text: 'Action Device Controls Settings', intent: 'android.settings.ACTION_DEVICE_CONTROLS_SETTINGS'),
  SettingIntent(id: 'action_media_controls_settings', text: 'Action Media Controls Settings', intent: 'android.settings.ACTION_MEDIA_CONTROLS_SETTINGS'),
  SettingIntent(id: 'show_admin_support_details', text: 'Show Admin Support Details', intent: 'android.settings.SHOW_ADMIN_SUPPORT_DETAILS'),
  SettingIntent(id: 'manage_supervisor_restricted_setting', text: 'Manage Supervisor Restricted Setting', intent: 'android.settings.MANAGE_SUPERVISOR_RESTRICTED_SETTING'),
  SettingIntent(id: 'show_remote_bugreport_dialog', text: 'Show Remote Bugreport Dialog', intent: 'android.settings.SHOW_REMOTE_BUGREPORT_DIALOG'),
  SettingIntent(id: 'vr_listener_settings', text: 'VR Listener Settings', intent: 'android.settings.VR_LISTENER_SETTINGS'),
  SettingIntent(id: 'picture_in_picture_settings', text: 'Picture In Picture Settings', intent: 'android.settings.PICTURE_IN_PICTURE_SETTINGS'),
  SettingIntent(id: 'storage_manager_settings', text: 'Storage Manager Settings', intent: 'android.settings.STORAGE_MANAGER_SETTINGS'),
  SettingIntent(id: 'webview_settings', text: 'Webview Settings', intent: 'android.settings.WEBVIEW_SETTINGS'),
  SettingIntent(id: 'enterprise_privacy_settings', text: 'Enterprise Privacy Settings', intent: 'android.settings.ENTERPRISE_PRIVACY_SETTINGS'),
  SettingIntent(id: 'show_work_policy_info', text: 'Show Work Policy Info', intent: 'android.settings.SHOW_WORK_POLICY_INFO'),
  SettingIntent(id: 'request_set_autofill_service', text: 'Request Set Autofill Service', intent: 'android.settings.REQUEST_SET_AUTOFILL_SERVICE'),
  SettingIntent(id: 'quick_access_wallet_settings', text: 'Quick Access Wallet Settings', intent: 'android.settings.QUICK_ACCESS_WALLET_SETTINGS'),
  SettingIntent(id: 'storage_volume_access_settings', text: 'Storage Volume Access Settings', intent: 'android.settings.STORAGE_VOLUME_ACCESS_SETTINGS'),
  SettingIntent(id: 'request_enable_content_capture', text: 'Request Enable Content Capture', intent: 'android.settings.REQUEST_ENABLE_CONTENT_CAPTURE'),
  SettingIntent(id: 'manage_domain_urls', text: 'Manage Domain URLs', intent: 'android.settings.MANAGE_DOMAIN_URLS'),
  SettingIntent(id: 'tether_settings', text: 'Tether Settings', intent: 'android.settings.TETHER_SETTINGS'),
  SettingIntent(id: 'wifi_tether_settings', text: 'WiFi Tether Settings', intent: 'com.android.settings.WIFI_TETHER_SETTINGS'),
  SettingIntent(id: 'enable_mms_data_request', text: 'Enable MMS Data Request', intent: 'android.settings.ENABLE_MMS_DATA_REQUEST'),
  SettingIntent(id: 'show_restricted_setting_dialog', text: 'Show Restricted Setting Dialog', intent: 'android.settings.SHOW_RESTRICTED_SETTING_DIALOG'),
  SettingIntent(id: 'extra_enable_mms_data_request_reason', text: 'Extra Enable MMS Data Request Reason', intent: 'android.settings.extra.ENABLE_MMS_DATA_REQUEST_REASON'),
  SettingIntent(id: 'mms_message_setting', text: 'MMS Message Setting', intent: 'android.settings.MMS_MESSAGE_SETTING'),
  SettingIntent(id: 'bedtime_settings', text: 'Bedtime Settings', intent: 'android.settings.BEDTIME_SETTINGS'),
];
